# Generated by Django 5.1 on 2024-08-26 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_alter_rickandmorty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Texto')),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Decimal')),
                ('date', models.DateField(verbose_name='Data')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('bool', models.BooleanField(default=False, verbose_name='Booleano')),
                ('situacao', models.CharField(choices=[('CONCLUIDO', 'Concluido'), ('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Situação')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk', to='app1.rickandmorty')),
                ('many', models.ManyToManyField(related_name='many', to='app1.rickandmorty')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Teste Campos',
            },
        ),
    ]
