# Generated by Django 5.1 on 2024-08-26 14:02

import TestesCampos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestesCampos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testecampos',
            name='imagem',
            field=models.ImageField(default='images\\generic_profile.png', upload_to=TestesCampos.models.image, verbose_name='Imagem do Personagem'),
        ),
    ]
