# Generated by Django 5.1 on 2024-08-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RickAndMorty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Personagem')),
                ('genero', models.CharField(max_length=10, verbose_name='Gênero do Personagem')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='Vivo ou Morto')),
                ('especie', models.CharField(blank=True, max_length=50, verbose_name='Especie do Personagem')),
                ('origem', models.CharField(blank=True, max_length=50, verbose_name='Origem do Personagem')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localizacao do Personagem')),
            ],
        ),
    ]
