# Generated by Django 5.1 on 2024-08-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rickandmorty',
            options={'verbose_name': 'Personagem', 'verbose_name_plural': 'Personagens'},
        ),
    ]
